package org.jboss.ddoyle.howtojboss.helloservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12-patch-02
 * Mon Sep 17 23:31:48 CEST 2012
 * Generated source version: 2.2.12-patch-02
 * 
 */
 
@WebService(targetNamespace = "http://www.jboss.org/ddoyle/howtojboss/HelloService/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "GetHello", targetNamespace = "http://www.jboss.org/ddoyle/howtojboss/HelloService/", className = "org.jboss.ddoyle.howtojboss.helloservice.GetHelloType")
    @WebMethod(operationName = "GetHello", action = "http://www.jboss.org/ddoyle/howtojboss/HelloService/GetHello")
    @ResponseWrapper(localName = "GetHelloResponse", targetNamespace = "http://www.jboss.org/ddoyle/howtojboss/HelloService/", className = "org.jboss.ddoyle.howtojboss.helloservice.GetHelloResponseType")
    public java.lang.String getHello(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
