
/*
 * 
 */

package org.jboss.ddoyle.howtojboss.paymentservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12-patch-02
 * Thu Sep 27 08:23:21 CEST 2012
 * Generated source version: 2.2.12-patch-02
 * 
 */


@WebServiceClient(name = "PaymentService", 
                  wsdlLocation = "file:/Users/mccloud/TestSetups/HowToJBoss-jBPM5_WebServices_integration/wsdl/PaymentService/PaymentService.wsdl",
                  targetNamespace = "http://www.jboss.org/ddoyle/howtojboss/PaymentService/") 
public class PaymentService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.jboss.org/ddoyle/howtojboss/PaymentService/", "PaymentService");
    public final static QName PaymentServiceSOAP = new QName("http://www.jboss.org/ddoyle/howtojboss/PaymentService/", "PaymentServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mccloud/TestSetups/HowToJBoss-jBPM5_WebServices_integration/wsdl/PaymentService/PaymentService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/Users/mccloud/TestSetups/HowToJBoss-jBPM5_WebServices_integration/wsdl/PaymentService/PaymentService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PaymentService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "PaymentServiceSOAP")
    public PaymentService getPaymentServiceSOAP() {
        return super.getPort(PaymentServiceSOAP, PaymentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentService
     */
    @WebEndpoint(name = "PaymentServiceSOAP")
    public PaymentService getPaymentServiceSOAP(WebServiceFeature... features) {
        return super.getPort(PaymentServiceSOAP, PaymentService.class, features);
    }

}
