
/*
 * 
 */

package org.jboss.ddoyle.howtojboss.worldservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12-patch-02
 * Mon Sep 17 23:32:45 CEST 2012
 * Generated source version: 2.2.12-patch-02
 * 
 */


@WebServiceClient(name = "WorldService", 
                  wsdlLocation = "file:/Users/mccloud/TestSetups/HowToJBoss-jBPM5_WebServices_integration/wsdl/WorldService/WorldService.wsdl",
                  targetNamespace = "http://www.jboss.org/ddoyle/howtojboss/WorldService/") 
public class WorldService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.jboss.org/ddoyle/howtojboss/WorldService/", "WorldService");
    public final static QName WorldServiceSOAP = new QName("http://www.jboss.org/ddoyle/howtojboss/WorldService/", "WorldServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mccloud/TestSetups/HowToJBoss-jBPM5_WebServices_integration/wsdl/WorldService/WorldService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/Users/mccloud/TestSetups/HowToJBoss-jBPM5_WebServices_integration/wsdl/WorldService/WorldService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public WorldService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WorldService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorldService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns WorldService
     */
    @WebEndpoint(name = "WorldServiceSOAP")
    public WorldService getWorldServiceSOAP() {
        return super.getPort(WorldServiceSOAP, WorldService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorldService
     */
    @WebEndpoint(name = "WorldServiceSOAP")
    public WorldService getWorldServiceSOAP(WebServiceFeature... features) {
        return super.getPort(WorldServiceSOAP, WorldService.class, features);
    }

}
