package org.jboss.ddoyle.howtojboss.worldservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12-patch-02
 * Mon Sep 17 23:32:45 CEST 2012
 * Generated source version: 2.2.12-patch-02
 * 
 */
 
@WebService(targetNamespace = "http://www.jboss.org/ddoyle/howtojboss/WorldService/", name = "WorldService")
@XmlSeeAlso({ObjectFactory.class})
public interface WorldService {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "GetWorld", targetNamespace = "http://www.jboss.org/ddoyle/howtojboss/WorldService/", className = "org.jboss.ddoyle.howtojboss.worldservice.GetWorldType")
    @WebMethod(operationName = "GetWorld", action = "http://www.jboss.org/ddoyle/howtojboss/WorldService/GetWorld")
    @ResponseWrapper(localName = "GetWorldResponse", targetNamespace = "http://www.jboss.org/ddoyle/howtojboss/WorldService/", className = "org.jboss.ddoyle.howtojboss.worldservice.GetWorldResponseType")
    public java.lang.String getWorld(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
